name: Playwright python tests

on:
  push:
    branches: ['main', 'master', 'dev']
  pull_request:
    branches: ['main', 'master', 'dev']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        continue-on-error: true
        run: pytest --alluredir=allure-results

      - name: Generate and publish Allure report
        uses: simple-elf/allure-report-action@v1.11
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_history: true
          keep_reports: 20

      - name: Upload Allure report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 10

      - name: Print Allure report link
        if: always()
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          echo "✅ Allure report published!"
          echo "🌐 Online report: https://${{ github.repository_owner }}.github.io/${REPO_NAME}/"
          echo "📦 Downloadable report available in Artifacts tab (as allure-report.zip)"
