name: Playwright python tests

on:
  push:
    branches: ['main', 'master', 'dev']
  pull_request:
    branches: ['main', 'master', 'dev']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        continue-on-error: true
        run: pytest --alluredir=allure-results

      - name: Upload Allure test results (raw data)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-raw
          path: allure-results

      - name: Build and Publish Allure Report
        uses: 'simple-elf/allure-report-action@v1.11'
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH-PAGES: gh-pages
        with:
          allure_results: allure-results